### ISSUE TITLE
Issue with HTMLParser

### ISSUE THREAD

**Issue by mary-tsekhmistrenko** [seisman/HinetPy#122] opened 2024-07-09 21:22 UTC
**Description of the problem**

I did not use HinetPy in a couple of months but it worked perfectly fine before. I did not change the conda environment, but after restarting some downloads I encountered the following issue. The problem seems to be with `parser.tabledata[i + 5]`, maybe the structure of the tabledata (from HTMLParser) might have changed?`parser.tabledata[i + 5]` gives me `'1' ` instead of an elevation value, e.g. `'175m'`

**Full code that generated the error**

Here is my minimum example where the error occurs.
```python
client = Client("your_username", "your_password")
sdate = datetime(2015,5,1, 0,0 ,0)
edate = datetime(2015,5,15, 0,0 ,0)

all_times = pd.date_range(sdate, edate-timedelta(minutes=30),freq="30min")
for downloadspan in all_times:
    date_string = '{}{:02d}{:02d}{:02d}{:02d}'.format(all_times[0].year, all_times[0].month, all_times[0].day, all_times[0].hour, all_times[0].minute)
    data, ctable = client.get_continuous_waveform("0101", date_string, 60*30)

```

**Full error message**

```
Traceback (most recent call last):
  File "download_hinet.py", line 21, in <module>
    data, ctable = client.get_continuous_waveform("0101", date_string, 60*30)
  File "/home/maria/Codes/NIED_Hi-net/HinetPy/HinetPy/client.py", line 467, in get_continuous_waveform
    self._max_span = self._get_allowed_span(code)
  File "/home/maria/Codes/NIED_Hi-net/HinetPy/HinetPy/client.py", line 1233, in _get_allowed_span
    stations = len(self.get_selected_stations(code))
  File "/home/maria/Codes/NIED_Hi-net/HinetPy/HinetPy/client.py", line 1051, in get_selected_stations
    elevation=float(parser.tabledata[i + 5].strip("m")),
ValueError: could not convert string to float: ''
```

**Expected behavior**

I expect the download to start as it did before. 

**System information**

- OS: Linux 
- Python version: 3.8.16
- HinetPy version: v0.9.0

**Comment by seisman** [comment] 2024-07-10 01:36
I can't reproduce it yet. Could you please visit the Hi-net website and check your current selection of stations by clicking the link as shown in the red box below:

<img width="819" alt="image" src="https://github.com/seisman/HinetPy/assets/3974108/c3d055b2-2273-48e8-bc6b-bfdf6a9a38a5">

Please post a screenshot of your station selections.

**Comment by mary-tsekhmistrenko** [comment] 2024-07-12 12:51
Thank you for your quick response. Here is the screenshot from my configuration:

![Screenshot 2024-07-12 at 14 50 13](https://github.com/user-attachments/assets/2d5fdcc5-6b32-4fe1-991d-e283da048d92)

(It has in total 72 stations, but I assume you do not need to see all of them?)

**Comment by seisman** [comment] 2024-07-12 14:47
@mary-tsekhmistrenko 

It's still unclear what's happening but I have made a fix and published v0.9.1 a few minutes ago. Please give it a try and let me know if it works.

**Comment by seisman** [comment] 2024-07-21 10:18
Closing the issue. Feel free to reopen it.

**Closed by seisman** 2024-07-21 10:18 UTC

**Comment by mary-tsekhmistrenko** [comment] 2024-08-19 08:07
It works now as before. Thanks for the update!
